import styles from '../styles/Home.module.css'
import Head from 'next/head';
import { app } from '../firebaseConfig';
import { useEffect } from 'react';
import {
    getAuth,
    createUserWithEmailAndPassword,
    GoogleAuthProvider,
    GithubAuthProvider,
    signInWithPopup,
    updateProfile
} from 'firebase/auth'
import { useState } from 'react';
import { useRouter } from 'next/router';
export default function Register() {
    const auth = getAuth();
    const googleProvider = new GoogleAuthProvider();
    const githubProvider = new GithubAuthProvider();
    const router = useRouter();
    const [email, setEmail] = useState('');
    const [name, setName] = useState('');
    const [password, setPassword] = useState('');
    const [user , setUser] =useState('')
    // var cuser = auth.currentUser;
    const signUp = () => {

        createUserWithEmailAndPassword(auth, email, password)
            .then((response) => {
                console.log(response.user)
                console.log(name)
                sessionStorage.setItem('Token', response.user.accessToken);
                sessionStorage.setItem('name', name);
                console.log(sessionStorage)
                // console.log(auth.currentUser)
                updateProfile(auth.currentUser,{
                    displayName: name
                  }).then((response) =>{
                    console.log('Update successful.')
                    // Update successful.
                    router.push('/home')
                  }, function(error) {
                   console.log(error)
                });  
                
            })

            // updateProfile(auth.currentUser,{
            //     displayName: name
            //   }).then((response) =>{
            //     console.log(response)
            //     // Update successful.
            //     // router.push('/home')
            //   }, function(error) {
            //     // An error happened.
            // });    
    }

    const signUpWithGoogle = () => {
        signInWithPopup(auth, googleProvider)
            .then((response) => {
                sessionStorage.setItem('Token', response.user.accessToken)
                console.log(response)
                console.log(auth)
                setUser(response.user)
                router.push('/home')
            })
    }

    const signUpWithGithub = () => {
        signInWithPopup(auth, githubProvider)
            .then((response) => {
                sessionStorage.setItem('Token', response.user.accessToken)
                console.log(response.user)
                router.push('/home')
            })
            .catch(err => {
                alert('Email Already Exists')
            })
    }

    useEffect(() => {
        let token = sessionStorage.getItem('Token')

        if(token){
            router.push('/home')
        }
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Next AUTH</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Register</h1>
                <input
                    placeholder='Name'
                    className={styles.inputBox}
                    onChange={(event) => setName(event.target.value)}
                    value={name}
                    type='name'
                />
                <input
                    placeholder='Email'
                    className={styles.inputBox}
                    onChange={(event) => setEmail(event.target.value)}
                    value={email}
                    type='email'
                />
                <input
                    placeholder='Password'
                    className={styles.inputBox}
                    onChange={(event) => setPassword(event.target.value)}
                    value={password}
                    type='password'
                />

                <button
                    className={styles.button}
                    onClick={signUp}
                >Sign Up</button>
                <hr />
                <button
                    className={styles.googleAlt}
                    onClick={signUpWithGoogle}>
                    Sign Up with Google
                </button>
                <hr />
                <button
                    onClick={signUpWithGithub}
                    className={styles.googleAlt}>
                    Sign Up with Github
                </button>
            </main>
        </div>
    )
}